#############################################################################
#                                                                           #
#                   Autorank 2 Advanced Config                              #
#                                                                           #
#   Please use the SimpleConfig unless you know what you are doing and      #
#   need functionality that the SimpleConfig doesn't provide.               #
#                                                                           #
#############################################################################

ranks:
    V000:
        requirements:
            time:
                value: 1h
        results:
            rank change: V000;R000
            command: 'say &p got to R000' 


    R000:
        requirements:
            time:
                value: 3h
            money:
                value: 1
        results:
            rank change: R000;R00C
            command: 'say &p got to R00C! try command /R00C' 


    E100:
        requirements:
            time:
                value: 9h
            money:
                value: 3
        results:
            rank change: E100;E10C
            command: 'say &p got to E10C! try command /E10C' 

    F100:
        requirements:
            time:
                value: 9h
            money:
                value: 3
        results:
            rank change: F100;F10C
            command: 'say &p got to F10C! try command /F10C' 

    W100:
        requirements:
            time:
                value: 9h
            money:
                value: 3
        results:
            rank change: W100;W10C
            command: 'say &p got to W10C! try command /W10C' 

    T100:
        requirements:
            time:
                value: 9h
            money:
                value: 3
        results:
            rank change: T100;T10C
            command: 'say &p got to T10C! try command /T10C' 

    E200:
        requirements:
            time:
                value: 15h
            money:
                value: 3
        results:
            rank change: E200;E20C
            command: 'say &p got to E20C! try command /E20C' 

    F200:
        requirements:
            time:
                value: 15h
            money:
                value: 3
        results:
            rank change: F200;F20C
            command: 'say &p got to F20C! try command /F20C' 

    W200:
        requirements:
            time:
                value: 15h
            money:
                value: 3
        results:
            rank change: W200;W20C
            command: 'say &p got to W20C! try command /W20C' 

    T200:
        requirements:
            time:
                value: 15h
            money:
                value: 3
        results:
            rank change: T200;T20C
            command: 'say &p got to T20C! try command /T20C' 

    E3A0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: E3A0;E3AC
            command: 'say &p got to E3AC! try command /E3AC'

    E3B0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: E3B0;E3BC
            command: 'say &p got to E3BC! try command /E3BC' 

    F3A0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: F3A0;F3AC
            command: 'say &p got to F3AC! try command /F3AC' 

    F3B0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: F3B0;F3BC
            command: 'say &p got to F3BC! try command /F3BC' 

    W3A0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: W3A0;W3AC
            command: 'say &p got to W3AC! try command /W3AC'

    W3B0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: W3B0;W3BC
            command: 'say &p got to W3BC! try command /W3BC'

    T3A0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: T3A0;T3AC
            command: 'say &p got to T3AC! try command /T3AC'

    T3B0:
        requirements:
            time:
                value: 20h
            money:
                value: 3
        results:
            rank change: T3B0;T3BC
            command: 'say &p got to T3BC! try command /T3BC'



            
# new requirements and results can be added by other plugins that hook into the Autorank API
# these are the ones that are included in the main plugin:
# 
#   requirements:
#       time: 1d 1h 1m
#       exp: 20 (level)
#       money: 2000 (requires vault ! Player has to have at least this amount of money)
#       world: world_nether (player has to be in this world to get ranked)
#       gamemode: 1 (player has to have a certain gamemode, 0 = Survival mode, 1 = Creative mode, 2 = Adventure mode)
#       has item: id(;amount;data;name) (checks the players inventory for the item, the name would be the display name of the item)
#       blocks broken: id(;amount;data;name) (a player has to have broken x amount blocks of item id and data) (Requires Stats) (when no data or amount is given, it will check total blocks)
#       Example: break 10 magenta wool would be: 'blocks broken: 35;10;2' 35 = itemid, 10 = amount, 2 = damagevalue
#       blocks placed: id(;amount;data) (a player has to have placed x amount blocks of item id and data) (Requires Stats) (when no data or amount is given, it will check total blocks)
#       votes: 10 (player has to have voted at least 10 times) (Requires Stats and Votifier)
#       damage taken: 10 (player has to have taken 10 damage) (damage is not counted in hearts) (Requires Stats)
#       mobs killed: 5;spider (player has to have killed 5 spiders) (if no entity is specified, then any kill counts) (Requires Stats) (for a list of entities: http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/EntityType.html)
#       location: x;y;z;world;radius (player has to be in a location or within its radius)
#       faction power: 10 (Amount of power a faction has to have) (Requires Factions)
#       players killed: 10 (Player has to kill at least 10 players) (Requires Stats)
#       global time: 10d 1h 5m (Player has to be online for at least 10 days, 1 hour and 5 mins) (Global time is the accumulated time over all servers you have connected the MySQL database with)
#       total time: 50d 1h (Player has to be with this server for at least 50 days and 1 hour) (The time from when the player joined for the first time is the reference point. This means that when a player has joined 3 weeks ago, his 'total time' = 3 weeks)
#       blocks moved: 1000;0 (Player has to move at least an x amount of blocks. Second argument is what kind of movement: 0=walk, 1=boat, 2=train, 3=pig, 4=pig in train, 5=horse) (Need Stats for this)
#       worldguard region: TestRegion (Player has to be in a certain WorldGuard region) (requires WorldGuard)
#       mcmmo skill level: 100;mining (Player has to have at least level 100 in mining) (requires McMMO)
#       mcmmo power level: 100 (Player has to have at least power level 100) (requires McMMO)
#       permission: i.need.a.permission (Player has to have this permission)
#       fish caught: 10 (Player has to have caught at least 10 fish) (requires Stats)
#       items crafted: 7 (Player has to have crafted at least 7 items) (requires Stats)
#       times sheared: 15 (Player has to have sheared at least 15 sheep) (requires Stats)
#
#   results:
#       rank change: new-rank
#       rank change: old-rank; new-rank
#       rank change: old-rank; new-rank; world (only works for permissions plugins that support this)
#       message: 'You got ranked up'
#       command: 'say &p hi; give &p 1 100'(executes a console command. &p will be replaced by the player name) You can perform more commands with the ';' sign.
#       effect: STEP_SOUND;8 (first argument is the effect name, second is the effect data. For a list of possible effects go to http://jd.bukkit.org/rb/doxygen/d8/db9/enumorg_1_1bukkit_1_1Effect.html)
#       tp: x;y;z;world;yaw;pitch (tp: 0;0;0;world_nether;1.0;2.0)
#       firework: target;power;type;R;G;B (Spawn a firework with on a player or spawn, with specified power, type and RGB colour) (target can be 'player' or 'spawn', power is an integer, type is a type (see http://jd.bukkit.org/rb/doxygen/d0/d54/enumorg_1_1bukkit_1_1FireworkEffect_1_1Type.html), R;G;B is a RGB colour code (see http://www.rapidtables.com/web/color/RGB_Color.htm))
